sudo: required
dist: xenial

language: python

python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8-dev"

stages:
  - test
  - name: codacy
    if: branch = master AND type = push

install:
  - travis_retry pip install -U tox-travis

script:
  - tox

after_success:
  - travis_retry pip install -U codecov
  - codecov


jobs:
  include:
    - stage: test
      if: branch = master AND type = push
      skip_cleanup: true
    - stage: codacy
      name: "Update codacy"
      script:
        - tox -e upload_coverage
