sudo: required
dist: xenial

language: python

python:
  - "3.5"
  - "3.6"
  - "3.7"

install:
  - travis_retry pip install -U tox-travis

script:
  - tox

after_success:
  - travis_retry pip install -U codecov
  - codecov
